### ISSUE TITLE
Error while running "CVE database recording in progress" - decoding issue

### ISSUE THREAD

**Issue by sdmzn** [Guezone/SECMON#10]
RSS news database recording in progress...

Successful build database.

CVE database recording in progress...This operation can take a few minutes to a few hours. Take a coffee! :D

ERROR
################## NEW SCRIPT ERROR AT 11/06/2021, 00:34:31 ##################
Traceback (most recent call last):
  File "/var/www/secmon/secmon_lib.py", line 564, in registerNewCve
    nvd_data = nvd_response.json()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
None

**Comment by sdmzn** [comment]
Running on Linux 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

**Comment by alb-uss** [comment]
@sdmzn Hi, can you contact me on Discord for take more informations please ? SECMON Discord link : https://discord.gg/cXzvb4fKzE Thx for advance

**Comment by SonuKhanPK** [comment]
Same issue with me:

![image](https://user-images.githubusercontent.com/85409484/121813324-fb5f2c80-cc84-11eb-921d-f044669a04ae.png)

**Comment by alb-uss** [comment]
@SonuKhanPK @sdmzn Hi guys, please check if my last commit have correcting this issue 

Thx for advance 👍
