### ISSUE TITLE
URL : https://mydomain/tasks 

### ISSUE THREAD

**Issue by mohammadkamrani** [Guezone/SECMON#12]
![2021-07-12_11-35-48](https://user-images.githubusercontent.com/53512886/125245277-9fc8a300-e305-11eb-977f-762d52080394.jpg)

**Comment by alb-uss** [comment]
Hi, please give me the return of this command : (echo "import sys" ; echo "print(sys.getdefaultencoding())") | python3

Thx for advance

**Comment by mohammadkamrani** [comment]
> (echo "import sys" ; echo "print(sys.getdefaultencoding())") | python3

Hi, sure
Here you are
"utf-8"

**Comment by alb-uss** [comment]
Please contact me on the Discord and send me the "logs.txt" file. I let you anonymize it if you want. I will try to see where can come from this encoding problem.....
