### ISSUE TITLE
https://IP/vuln-mgmt 

### ISSUE THREAD

**Issue by mohammadkamrani** [Guezone/SECMON#15]
![2021-07-13_15-27-46](https://user-images.githubusercontent.com/53512886/125440609-f859757d-9d17-42ff-8f34-1793ba3a6661.jpg)

**Comment by alb-uss** [comment]
Corrected with 7d4bd103517b9e6989a712d13745022f5229c81a. @mohammadkamrani please check its all good ;)

**Comment by mohammadkamrani** [comment]
Thanks, @Guezone, it works
