### ISSUE TITLE
CSV import product error

### ISSUE THREAD

**Issue by kit567** [Guezone/SECMON#18]
I got an error when trying to import from CSV:

Unexpected error
Oops. SECMON has encountered an error!

From apache.log:

[Fri Jul 23 13:34:59.745870 2021] [wsgi:error] [pid 9726:tid 140063431202560] [remote 192.168.28.224:52852] ################## NEW GUI ERROR AT 23/07/2021, 13:34:59 ##################
[Fri Jul 23 13:34:59.746239 2021] [wsgi:error] [pid 9726:tid 140063431202560] [remote 192.168.28.224:52852] ######## URL : https://10.5.6.133/product-mgmt ##########
[Fri Jul 23 13:34:59.747316 2021] [wsgi:error] [pid 9726:tid 140063431202560] [remote 192.168.28.224:52852] Traceback (most recent call last):
[Fri Jul 23 13:34:59.747363 2021] [wsgi:error] [pid 9726:tid 140063431202560] [remote 192.168.28.224:52852]   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
[Fri Jul 23 13:34:59.747368 2021] [wsgi:error] [pid 9726:tid 140063431202560] [remote 192.168.28.224:52852]     rv = self.dispatch_request()
[Fri Jul 23 13:34:59.747373 2021] [wsgi:error] [pid 9726:tid 140063431202560] [remote 192.168.28.224:52852]   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
[Fri Jul 23 13:34:59.747377 2021] [wsgi:error] [pid 9726:tid 140063431202560] [remote 192.168.28.224:52852]     return self.view_functions[rule.endpoint](**req.view_args)
[Fri Jul 23 13:34:59.747382 2021] [wsgi:error] [pid 9726:tid 140063431202560] [remote 192.168.28.224:52852]   File "/usr/local/lib/python3.7/dist-packages/flask_simplelogin/__init__.py", line 117, in simple_decorator
[Fri Jul 23 13:34:59.747385 2021] [wsgi:error] [pid 9726:tid 140063431202560] [remote 192.168.28.224:52852]     return dispatch(function, *args, **kwargs)
[Fri Jul 23 13:34:59.747389 2021] [wsgi:error] [pid 9726:tid 140063431202560] [remote 192.168.28.224:52852]   File "/usr/local/lib/python3.7/dist-packages/flask_simplelogin/__init__.py", line 98, in dispatch
[Fri Jul 23 13:34:59.747393 2021] [wsgi:error] [pid 9726:tid 140063431202560] [remote 192.168.28.224:52852]     return check(must) or fun(*args, **kwargs)
[Fri Jul 23 13:34:59.747397 2021] [wsgi:error] [pid 9726:tid 140063431202560] [remote 192.168.28.224:52852]   File "/var/www/secmon/secmon_web.py", line 687, in psearch
[Fri Jul 23 13:34:59.747400 2021] [wsgi:error] [pid 9726:tid 140063431202560] [remote 192.168.28.224:52852]     if filename.split(".")[1] == "csv" and len(filename.split(".")) == 2:
[Fri Jul 23 13:34:59.747419 2021] [wsgi:error] [pid 9726:tid 140063431202560] [remote 192.168.28.224:52852] IndexError: list index out of range
[Fri Jul 23 13:34:59.747431 2021] [wsgi:error] [pid 9726:tid 140063431202560] [remote 192.168.28.224:52852] None
[Fri Jul 23 13:34:59.747437 2021] [wsgi:error] [pid 9726:tid 140063431202560] [remote 192.168.28.224:52852] ################## PLEASE REPORT THIS ON GITHUB ##################

**Comment by alb-uss** [comment]
Hello ! can you contact me on the Discord (see the readme) and give me your CSV ? I will analyze the file and test this. Thx for advance

**Comment by kit567** [comment]
I try it again and import was successful
