### ISSUE TITLE
AttributeError: module 'base64' has no attribute 'decodestring'

### ISSUE THREAD

**Issue by leezopub** [Guezone/SECMON#24]
I install with docker and error, please help
![image](https://user-images.githubusercontent.com/91020993/133932656-118e7b7b-4130-4108-a51c-727075779413.png)

**Comment by alb-uss** [comment]
Hi,

The problem came from the version of feedparser which was using a base64 function. Can you update feedparser with the following command and tell me if everything is ok for you : pip install feedparser --upgrade

Thanks and have a nice day
