### ISSUE TITLE
Error on Web Pages Home & By Product veulnerabilities & cve_updater.py

### ISSUE THREAD

**Issue by Radvaroc53** [Guezone/SECMON#25]
**_log cve_updater.py_**

Updating high risk product list....
Traceback (most recent call last):
  File "cve_updater.py", line 53, in <module>
    plist = getFormatedProductList()
  File "/var/www/secmon/secmon_lib.py", line 860, in getFormatedProductList
    pvendor = disassmbled_cpe[3].replace("_"," ").title()
IndexError: list index out of range

**_log apache_**
[wsgi:error]

######## URL : http://secmon.local/by-product-vulns ##########
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.6/site-packages/flask_simplelogin/__init__.py", line 117, in simple_decorator
return dispatch(function, *args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/flask_simplelogin/__init__.py", line 98, in dispatch
return check(must) or fun(*args, **kwargs)
File "/var/www/secmon/secmon_web.py", line 602, in byProductVulns
plist = getFormatedProductList()
File "/var/www/secmon/secmon_lib.py", line 860, in getFormatedProductList
pvendor = disassmbled_cpe[3].replace("_"," ").title()
IndexError: list index out of range
None

**Comment by alb-uss** [comment]
Hi,

Do you have the latest version of SECMON? Normally, I have treated this problem in a commit (5e42a2002af20e13831d0c34b8ef279c712e1f80) of July 26 ? 

Thanks

**Comment by Jason-Linux** [comment]
Yes i have the last version available on your github.

**Comment by Jason-Linux** [comment]
what's changement between the actual and the last version ?

Le ven. 8 oct. 2021 à 16:10, Jason DUBOIS ***@***.***> a
écrit :

> Yes i have the last version available on your github.
>
>
>
>

**Comment by Radvaroc53** [comment]
After a new install with same version i don't have the problem but Now i have this issue :
![datetime](https://user-images.githubusercontent.com/32597298/136798718-0832f37a-e44c-4a96-95ee-9973c2dcd9ff.png)

fromisoformat don't exist for verion older than Pyhton 3.7

**Comment by Radvaroc53** [comment]
**Correctif :** 
**vim /var/www/secmon/secmon_lib.py**

_//Import datetime et backports_
from datetime import datetime, timedelta, date, time
from backports.datetime_fromisoformat import MonkeyPatch
MonkeyPatch.patch_fromisoformat()

after this restart
I precise i'm on **Rocky linux 8**

**Comment by alb-uss** [comment]
Hello @Radvaroc53,

I changed the format of the errors, now the variables appear in the traceback errors, this will allow me to understand why the error remains and will be used for the next debugs. Please update SECMON :

To do on the host : 
- Go in the SECMON folder which is in volume with the Docker container 
- git pull 

To do in the Docker container:  
pip3 install -r /var/www/secmon/requirements.txt
service apache2 restart

Retry your attempts on the web pages that have errors and return me the new errors. Also, for the datetime issue, please use the Python version that has been tested and visible in the README, i.e. at least Python 3.8.

Thanks a lot

**Comment by Radvaroc53** [comment]
Hi !
Sry for long time since last answer, last answer i sent you how correct the bug if using Python 3.6 after test on 3.8 I don't have **this** problem but i prefer install without docker, to keep 1 VM, 1 Feature, and have total control on the installation.
