### ISSUE TITLE
Product by Keyword not case sensitive

### ISSUE THREAD

**Issue by frostnite** [Guezone/SECMON#30]
Product by Keyword not case sensitive.

As seen on below screenshot, I need to add the product keyword "NumPy" to get the other remaining 2 CVE for numpy. 
Whereas the product with keyword "numpy" only managed to identify 2 CVE which actually possible to be 4 CVE.

![image](https://user-images.githubusercontent.com/14076246/146742063-e7479c52-3f06-47a6-8eb7-c883f8eb7041.png)

![image](https://user-images.githubusercontent.com/14076246/146742291-0c1bd2a4-40ff-41d7-8413-e8c059676e3c.png)

**Comment by alb-uss** [comment]
Hello @frostnite,

Indeed, the keywords are case-sensitive for the moment and this is part of my road map. However, in general, the product names are almost always in the same form, here we see that we always find the form "NumPy" in the screenshot. It is therefore necessary to choose the real form of the product name (a little heavy I concieve).

I take this opportunity to update the road map, thanks to you! :)

**Comment by frostnite** [comment]
> Hello @frostnite,
> 
> Indeed, the keywords are case-sensitive for the moment and this is part of my road map. However, in general, the product names are almost always in the same form, here we see that we always find the form "NumPy" in the screenshot. It is therefore necessary to choose the real form of the product name (a little heavy I concieve).
> 
> I take this opportunity to update the road map, thanks to you! :)

You mean its not case sensitive right? Anyways I have added .lower() to both key and summary variables in cvepoller.py which actually resolve the issue for me.
