### ISSUE TITLE
Impossible use Https

### ISSUE THREAD

**Issue by Jason-Linux** [Guezone/SECMON#32]
Hi,
When i would like to add https tls 1.3 on my webserver, and when i would like to consult your web app i access on httpd default pages.
Conf : http://pastebin.fr/101659

**Comment by alb-uss** [comment]
Hi, please give me more details :

- OS and version 
- Deployment mode (Docker or legacy)

Thx

**Comment by Jason-Linux** [comment]
OS : RockyLinux 8.5
Python 3.8
Package : HTTPD
Deployment : Legacy

**Comment by alb-uss** [comment]
Hello,

Thank you for your feedback. SECMON has never been tested on RHEL based OS. If you want to keep this OS at all costs, I strongly advise you to use the Docker deployable version. As the documentation is not RHEL based, the commands to install the product, I invite you to adapt the doc according to your OS if you really want to stay in legacy on RockyLinux.

Guezone
