### ISSUE TITLE
Communicate with another website

### ISSUE THREAD

**Issue by Jason-Linux** [Guezone/SECMON#33]
Hello,

does it possible to commuicate with secmon to another website ?

Best regards,

**Comment by alb-uss** [comment]
Hello,

What is the purpose of having it communicate with another website? If the goal is to retrieve raw data in web API, it is not yet possible (it is in the roadmap). If you wish, the project is open to collaboration if you are interested in participating in the API part.

Best regards,

Guezone

**Comment by Jason-Linux** [comment]
Hi,

I don't know how dev an API but if i work on it i send this.

Thanks for your answer,

Best Regards,

Jason
