### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by SonuKhanPK** [Guezone/SECMON#7]
> [Sun Jun 06 11:41:17.411550 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610] ################## NEW GUI ERROR AT 06/06/2021, 11:41:17 ##################
> [Sun Jun 06 11:41:17.411729 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610] ######## URL : http://192.168.244.140/tasks ##########
> [Sun Jun 06 11:41:17.415130 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610] Traceback (most recent call last):
> [Sun Jun 06 11:41:17.415169 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
> [Sun Jun 06 11:41:17.415174 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610]     rv = self.dispatch_request()
> [Sun Jun 06 11:41:17.415180 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
> [Sun Jun 06 11:41:17.415184 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610]     return self.view_functions[rule.endpoint](**req.view_args)
> [Sun Jun 06 11:41:17.415189 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610]   File "/usr/local/lib/python3.8/dist-packages/flask_simplelogin/__init__.py", line 117, in simple_decorator
> [Sun Jun 06 11:41:17.415193 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610]     return dispatch(function, *args, **kwargs)
> [Sun Jun 06 11:41:17.415198 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610]   File "/usr/local/lib/python3.8/dist-packages/flask_simplelogin/__init__.py", line 98, in dispatch
> [Sun Jun 06 11:41:17.415201 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610]     return check(must) or fun(*args, **kwargs)
> [Sun Jun 06 11:41:17.415207 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610]   File "/var/www/secmon/secmon_web.py", line 612, in tasks
> [Sun Jun 06 11:41:17.415210 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610]     tasks = getTasks()
> [Sun Jun 06 11:41:17.415215 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610]   File "/var/www/secmon/secmon_lib.py", line 262, in getTasks
> [Sun Jun 06 11:41:17.415218 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610]     for line in reversed(list(open(logfile))):
> [Sun Jun 06 11:41:17.415224 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610]   File "/usr/lib/python3.8/encodings/ascii.py", line 26, in decode
> [Sun Jun 06 11:41:17.415227 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610]     return codecs.ascii_decode(input, self.errors)[0]
> [Sun Jun 06 11:41:17.415239 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1312: ordinal not in range(128)
> [Sun Jun 06 11:41:17.415253 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610] None
> [Sun Jun 06 11:41:17.415262 2021] [wsgi:error] [pid 16043:tid 139847434086144] [remote 192.168.244.140:44610] ################## PLEASE REPORT THIS ON GITHUB ##################

**Comment by alb-uss** [comment]
@SonuKhanPK Please check that the latest commit corrects this error

**Comment by SonuKhanPK** [comment]
Yes, the issue is fixed now. Thanks.
