### ISSUE TITLE
wsgi:error GUI Error

### ISSUE THREAD

**Issue by muddydev** [Guezone/SECMON#8]
[Tue Jun 08 15:51:00.890407 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598] ################## NEW GUI ERROR AT 08/06/2021, 15:51:00 ##################
[Tue Jun 08 15:51:00.890587 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598] ######## URL : https://secmon.companyname.com/by-product-vulns ##########
[Tue Jun 08 15:51:00.891434 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598] Traceback (most recent call last):
[Tue Jun 08 15:51:00.891479 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
[Tue Jun 08 15:51:00.891484 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598]     rv = self.dispatch_request()
[Tue Jun 08 15:51:00.891493 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
[Tue Jun 08 15:51:00.891497 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Jun 08 15:51:00.891504 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598]   File "/usr/local/lib/python3.8/dist-packages/flask_simplelogin/__init__.py", line 117, in simple_decorator
[Tue Jun 08 15:51:00.891523 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598]     return dispatch(function, *args, **kwargs)
[Tue Jun 08 15:51:00.891532 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598]   File "/usr/local/lib/python3.8/dist-packages/flask_simplelogin/__init__.py", line 98, in dispatch
[Tue Jun 08 15:51:00.891537 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598]     return check(must) or fun(*args, **kwargs)
[Tue Jun 08 15:51:00.891547 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598]   File "/var/www/secmon/secmon_web.py", line 584, in byProductVulns
[Tue Jun 08 15:51:00.891551 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598]     product = request.form['product_selection']
[Tue Jun 08 15:51:00.891562 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598]   File "/usr/local/lib/python3.8/dist-packages/werkzeug/datastructures.py", line 442, in __getitem__
[Tue Jun 08 15:51:00.891567 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598]     raise exceptions.BadRequestKeyError(key)
[Tue Jun 08 15:51:00.891588 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598] werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
[Tue Jun 08 15:51:00.891605 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598] None
[Tue Jun 08 15:51:00.891614 2021] [wsgi:error] [pid 56526:tid 140361054099200] [remote internalIP:3598] ################## PLEASE REPORT THIS ON GITHUB ##################

**Comment by alb-uss** [comment]
@muddydev Please check that the latest commit corrects this error
