### ISSUE TITLE
local variable 'letter' referenced before assignment

### ISSUE THREAD

**Issue by muddydev** [Guezone/SECMON#9]
[Tue Jun 08 15:49:24.473654 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472] ################## NEW GUI ERROR AT 08/06/2021, 15:49:24 ##################
[Tue Jun 08 15:49:24.473846 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472] ######## URL : https://secmon.companyname.com/reports ##########
[Tue Jun 08 15:49:24.473990 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472] Traceback (most recent call last):
[Tue Jun 08 15:49:24.474028 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
[Tue Jun 08 15:49:24.474035 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472]     rv = self.dispatch_request()
[Tue Jun 08 15:49:24.474042 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472]   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
[Tue Jun 08 15:49:24.474046 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Jun 08 15:49:24.474053 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472]   File "/usr/local/lib/python3.8/dist-packages/flask_simplelogin/__init__.py", line 117, in simple_decorator
[Tue Jun 08 15:49:24.474056 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472]     return dispatch(function, *args, **kwargs)
[Tue Jun 08 15:49:24.474062 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472]   File "/usr/local/lib/python3.8/dist-packages/flask_simplelogin/__init__.py", line 98, in dispatch
[Tue Jun 08 15:49:24.474067 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472]     return check(must) or fun(*args, **kwargs)
[Tue Jun 08 15:49:24.474076 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472]   File "/var/www/secmon/secmon_web.py", line 541, in reports
[Tue Jun 08 15:49:24.474081 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472]     generateCveReport(datetime.strptime("01/01/2020", "%d/%m/%Y"),datetime.strptime("01/01/2020", "%d/%m/%Y"),isFull=True)
[Tue Jun 08 15:49:24.474091 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472]   File "/var/www/secmon/secmon_lib.py", line 149, in generateCveReport
[Tue Jun 08 15:49:24.474097 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472]     sheet["{}1".format(letter)].font = bold_font
[Tue Jun 08 15:49:24.474115 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472] UnboundLocalError: local variable 'letter' referenced before assignment
[Tue Jun 08 15:49:24.474133 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472] None
[Tue Jun 08 15:49:24.474143 2021] [wsgi:error] [pid 56526:tid 140361087670016] [remote internalIP:2472] ################## PLEASE REPORT THIS ON GITHUB ##################

**Comment by alb-uss** [comment]
d8e8744fca76b54549971bf22d19bce1544d9b33
